// <auto-generated />
using System;
using LocalIotScanner.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalIotScanner.Core.Migrations
{
    [DbContext(typeof(ScannerDbContext))]
    partial class ScannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LocalIotScanner.Core.Models.AuditSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverallRiskScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subnet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalHostsFound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditSessions");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditSessionId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.ScannedPort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ScannedPorts");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScannedPortId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedPortId");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.Device", b =>
                {
                    b.HasOne("LocalIotScanner.Core.Models.AuditSession", "AuditSession")
                        .WithMany("Devices")
                        .HasForeignKey("AuditSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditSession");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.ScannedPort", b =>
                {
                    b.HasOne("LocalIotScanner.Core.Models.Device", "Device")
                        .WithMany("ScannedPorts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.Vulnerability", b =>
                {
                    b.HasOne("LocalIotScanner.Core.Models.ScannedPort", "ScannedPort")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("ScannedPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedPort");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.AuditSession", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.Device", b =>
                {
                    b.Navigation("ScannedPorts");
                });

            modelBuilder.Entity("LocalIotScanner.Core.Models.ScannedPort", b =>
                {
                    b.Navigation("Vulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
